error_log = /var/log/php/error.log
display_errors = On
display_startup_errors = On
log_errors = On
error_reporting = E_ALL
html_errors = On

opcache.jit = 0
opcache.jit_buffer_size = 0
opcache.jit_debug = 0
